name: Next.js CI/CD

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm manually
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Lint
      - run: pnpm lint

      # Typecheck
      - run: pnpm tsc --noEmit

      # Test
      - run: pnpm test -- --coverage

      # Build
      - run: pnpm build

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v4

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: ${{ github.ref == 'refs/heads/main' }}
